#!/bin/bash

PYFILE=../drawer.py

FILE=/media/ostocker/Data/OS/test_toulouse_SPOT7/v31_marseille
DATAIMG=/media/ostocker/ExtremeSSD/storage/spot7/mars/tiles_pxs
DATAGT=/media/ostocker/ExtremeSSD/storage/spot7/mars/tiles_pxs
STEP=$FILE/stepCrossVal_0

#Required
OUT=$STEP
STATE=$STEP/states/model_best.pth.tar
IMG=$DATAIMG/tiles
METAIMG=$DATAIMG/meta_img.h5

#false or path
GT=$DATAGT/tiles_gt
METAGT=$DATAGT/meta_gt.h5
CV=$STEP/crossValID.pckl
COLOR=false

#booleans
INF=true
DIF=false
PROBA=false
PROBAH5=false
METRIC=true
CUDA=true

#values
MARGIN=30
BS=15
NODATA=99
WORKERS=10



python $PYFILE -state $STATE -meta_img $METAIMG -meta_gt $METAGT -dir_img $IMG -dir_gt $GT -out $OUT -bs $BS -cv $CV -inf $INF -dif $DIF -proba $PROBA -probaH5 $PROBAH5 -nodata $NODATA -color $COLOR -metric $METRIC -cuda $CUDA -num_workers $WORKERS -margin $MARGIN
