#!/bin/bash

PYFILE=../main.py

FILE=/media/ostocker/Data/OS/test_toulouse_SPOT7/v31_marseille
DATAIMG=/media/ostocker/ExtremeSSD/storage/spot7/mars/tiles_pxs
DATAGT=/media/ostocker/ExtremeSSD/storage/spot7/mars/tiles_pxs

#Required
OUT=$FILE
IMG=$DATAIMG/tiles
METAIMG=$DATAIMG/meta_img.h5
GT=$DATAGT/tiles_gt
METAGT=$DATAGT/meta_gt.h5

#false or path
STATE=false
SEED=/home/ostocker/deep/data/seed.dump
SELECTION=$DATAIMG/data_selection

#values
BS=16
EPOCH=150
ITER=1
SPLIT=5
MEM=4
LR=1e-2
WORKERS=10
NODATA=99

#booleans
AUG=false
CUDA=true


python $PYFILE -dir_img $IMG -dir_gt $GT -meta_img $METAIMG -meta_gt $METAGT -out $OUT -bs $BS -e $EPOCH -cvIter $ITER -cvSplit $SPLIT -mem $MEM -aug $AUG -nodata $NODATA -selection $SELECTION -seed $SEED -num_workers $WORKERS -state $STATE



